### ISSUE TITLE
how to download the source code and models?

### ISSUE THREAD

**Issue by swjtuccy** [MalongTech/CurriculumNet#2]
thank u ,appreciate your help

**Comment by mscottml** [comment]
Hi @swjtuccy , models which can be used to verify our results from the paper are linked here:
https://github.com/MalongTech/research-curriculumnet/tree/master/models

The source code for the clustering algorithm in the paper is available here:
https://github.com/MalongTech/research-curriculumnet/tree/master/curriculum_clustering

If you are having trouble downloading the models, please let me know. It is currently hosted on AWS China.
